/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bootcamp Treinos API
 * API para o bootcamp de treinos do FSC
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from '../../fetch';
export type PostWorkoutPlansBodyWorkoutDaysItemWeekDay = typeof PostWorkoutPlansBodyWorkoutDaysItemWeekDay[keyof typeof PostWorkoutPlansBodyWorkoutDaysItemWeekDay];


export const PostWorkoutPlansBodyWorkoutDaysItemWeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;

export type PostWorkoutPlansBodyWorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type PostWorkoutPlansBodyWorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: PostWorkoutPlansBodyWorkoutDaysItemWeekDay;
  isRest?: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  /** @nullable */
  coverImageUrl?: string | null;
  exercises: PostWorkoutPlansBodyWorkoutDaysItemExercisesItem[];
};

export type PostWorkoutPlansBody = {
  /** @minLength 1 */
  name: string;
  workoutDays: PostWorkoutPlansBodyWorkoutDaysItem[];
};

export type PostWorkoutPlans201WorkoutDaysItemWeekDay = typeof PostWorkoutPlans201WorkoutDaysItemWeekDay[keyof typeof PostWorkoutPlans201WorkoutDaysItemWeekDay];


export const PostWorkoutPlans201WorkoutDaysItemWeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;

export type PostWorkoutPlans201WorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type PostWorkoutPlans201WorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: PostWorkoutPlans201WorkoutDaysItemWeekDay;
  isRest: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  /** @nullable */
  coverImageUrl?: string | null;
  exercises: PostWorkoutPlans201WorkoutDaysItemExercisesItem[];
};

export type PostWorkoutPlans201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  workoutDays: PostWorkoutPlans201WorkoutDaysItem[];
};

export type PostWorkoutPlans400 = {
  error: string;
  code: string;
};

export type PostWorkoutPlans401 = {
  error: string;
  code: string;
};

export type PostWorkoutPlans404 = {
  error: string;
  code: string;
};

export type PostWorkoutPlans500 = {
  error: string;
  code: string;
};

export type GetWorkoutPlansParams = {
active?: GetWorkoutPlansActive;
};

export type GetWorkoutPlansActive = typeof GetWorkoutPlansActive[keyof typeof GetWorkoutPlansActive];


export const GetWorkoutPlansActive = {
  true: 'true',
  false: 'false',
} as const;

export type GetWorkoutPlans200ItemWorkoutDaysItemWeekDay = typeof GetWorkoutPlans200ItemWorkoutDaysItemWeekDay[keyof typeof GetWorkoutPlans200ItemWorkoutDaysItemWeekDay];


export const GetWorkoutPlans200ItemWorkoutDaysItemWeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;

export type GetWorkoutPlans200ItemWorkoutDaysItemExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  order: number;
  name: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type GetWorkoutPlans200ItemWorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  weekDay: GetWorkoutPlans200ItemWorkoutDaysItemWeekDay;
  isRest: boolean;
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercises: GetWorkoutPlans200ItemWorkoutDaysItemExercisesItem[];
};

export type GetWorkoutPlans200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isActive: boolean;
  workoutDays: GetWorkoutPlans200ItemWorkoutDaysItem[];
};

export type GetWorkoutPlans401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlans500 = {
  error: string;
  code: string;
};

export type GetWorkoutPlansWorkoutPlanId200WorkoutDaysItemWeekDay = typeof GetWorkoutPlansWorkoutPlanId200WorkoutDaysItemWeekDay[keyof typeof GetWorkoutPlansWorkoutPlanId200WorkoutDaysItemWeekDay];


export const GetWorkoutPlansWorkoutPlanId200WorkoutDaysItemWeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;

export type GetWorkoutPlansWorkoutPlanId200WorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  weekDay: GetWorkoutPlansWorkoutPlanId200WorkoutDaysItemWeekDay;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  exercisesCount: number;
};

export type GetWorkoutPlansWorkoutPlanId200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  workoutDays: GetWorkoutPlansWorkoutPlanId200WorkoutDaysItem[];
};

export type GetWorkoutPlansWorkoutPlanId401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlansWorkoutPlanId404 = {
  error: string;
  code: string;
};

export type GetWorkoutPlansWorkoutPlanId500 = {
  error: string;
  code: string;
};

export type GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId200WeekDay = typeof GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId200WeekDay[keyof typeof GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId200WeekDay];


export const GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId200WeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;

export type GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId200ExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  order: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId200SessionsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$ */
  startedAt?: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$ */
  completedAt?: string;
};

export type GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  weekDay: GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId200WeekDay;
  exercises: GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId200ExercisesItem[];
  sessions: GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId200SessionsItem[];
};

export type GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId404 = {
  error: string;
  code: string;
};

export type GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId500 = {
  error: string;
  code: string;
};

export type PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userWorkoutSessionId: string;
};

export type PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions401 = {
  error: string;
  code: string;
};

export type PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions404 = {
  error: string;
  code: string;
};

export type PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions409 = {
  error: string;
  code: string;
};

export type PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions422 = {
  error: string;
  code: string;
};

export type PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions500 = {
  error: string;
  code: string;
};

export type PatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdBody = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
};

export type PatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionId200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  startedAt: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
};

export type PatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionId401 = {
  error: string;
  code: string;
};

export type PatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionId404 = {
  error: string;
  code: string;
};

export type PatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionId500 = {
  error: string;
  code: string;
};

export type GetHomeDate200TodayWorkoutDay = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  weekDay: string;
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercisesCount: number;
};

export type GetHomeDate200ConsistencyByDay = {[key: string]: {
  workoutDayCompleted: boolean;
  workoutDayStarted: boolean;
}};

export type GetHomeDate200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  activeWorkoutPlanId: string;
  todayWorkoutDay: GetHomeDate200TodayWorkoutDay;
  workoutStreak: number;
  consistencyByDay: GetHomeDate200ConsistencyByDay;
};

export type GetHomeDate401 = {
  error: string;
  code: string;
};

export type GetHomeDate404 = {
  error: string;
  code: string;
};

export type GetHomeDate500 = {
  error: string;
  code: string;
};

export type GetStatsParams = {
/**
 * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
 */
from: string;
/**
 * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
 */
to: string;
};

export type GetStats200ConsistencyByDay = {[key: string]: {
  workoutDayCompleted: boolean;
  workoutDayStarted: boolean;
}};

export type GetStats200 = {
  workoutStreak: number;
  consistencyByDay: GetStats200ConsistencyByDay;
  completedWorkoutsCount: number;
  conclusionRate: number;
  totalTimeInSeconds: number;
};

export type GetStats401 = {
  error: string;
  code: string;
};

export type GetStats404 = {
  error: string;
  code: string;
};

export type GetStats500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetMe200 = {
  userId: string;
  userName: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  /**
     * @minimum 0
     * @maximum 100
     */
  bodyFatPercentage: number;
} | null;

export type GetMe401 = {
  error: string;
  code: string;
};

export type GetMe500 = {
  error: string;
  code: string;
};

export type PutMeBody = {
  /** @minimum 0 */
  weightInGrams: number;
  /** @minimum 0 */
  heightInCentimeters: number;
  /** @minimum 0 */
  age: number;
  /**
     * @minimum 0
     * @maximum 100
     */
  bodyFatPercentage: number;
};

export type PutMe200 = {
  userId: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  bodyFatPercentage: number;
};

export type PutMe401 = {
  error: string;
  code: string;
};

export type PutMe500 = {
  error: string;
  code: string;
};

export type Get200 = {
  message: string;
};

/**
 * @summary Create a new workout plan
 */
export type postWorkoutPlansResponse201 = {
  data: PostWorkoutPlans201
  status: 201
}

export type postWorkoutPlansResponse400 = {
  data: PostWorkoutPlans400
  status: 400
}

export type postWorkoutPlansResponse401 = {
  data: PostWorkoutPlans401
  status: 401
}

export type postWorkoutPlansResponse404 = {
  data: PostWorkoutPlans404
  status: 404
}

export type postWorkoutPlansResponse500 = {
  data: PostWorkoutPlans500
  status: 500
}

export type postWorkoutPlansResponseSuccess = (postWorkoutPlansResponse201) & {
  headers: Headers;
};
export type postWorkoutPlansResponseError = (postWorkoutPlansResponse400 | postWorkoutPlansResponse401 | postWorkoutPlansResponse404 | postWorkoutPlansResponse500) & {
  headers: Headers;
};

export type postWorkoutPlansResponse = (postWorkoutPlansResponseSuccess | postWorkoutPlansResponseError)

export const getPostWorkoutPlansUrl = () => {




  return `/workout-plans/`
}

export const postWorkoutPlans = async (postWorkoutPlansBody: PostWorkoutPlansBody, options?: RequestInit): Promise<postWorkoutPlansResponse> => {

  return customFetch<postWorkoutPlansResponse>(getPostWorkoutPlansUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postWorkoutPlansBody,)
  }
);}



/**
 * @summary List workout plans
 */
export type getWorkoutPlansResponse200 = {
  data: GetWorkoutPlans200Item[]
  status: 200
}

export type getWorkoutPlansResponse401 = {
  data: GetWorkoutPlans401
  status: 401
}

export type getWorkoutPlansResponse500 = {
  data: GetWorkoutPlans500
  status: 500
}

export type getWorkoutPlansResponseSuccess = (getWorkoutPlansResponse200) & {
  headers: Headers;
};
export type getWorkoutPlansResponseError = (getWorkoutPlansResponse401 | getWorkoutPlansResponse500) & {
  headers: Headers;
};

export type getWorkoutPlansResponse = (getWorkoutPlansResponseSuccess | getWorkoutPlansResponseError)

export const getGetWorkoutPlansUrl = (params?: GetWorkoutPlansParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/workout-plans/?${stringifiedParams}` : `/workout-plans/`
}

export const getWorkoutPlans = async (params?: GetWorkoutPlansParams, options?: RequestInit): Promise<getWorkoutPlansResponse> => {

  return customFetch<getWorkoutPlansResponse>(getGetWorkoutPlansUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Get a workout plan
 */
export type getWorkoutPlansWorkoutPlanIdResponse200 = {
  data: GetWorkoutPlansWorkoutPlanId200
  status: 200
}

export type getWorkoutPlansWorkoutPlanIdResponse401 = {
  data: GetWorkoutPlansWorkoutPlanId401
  status: 401
}

export type getWorkoutPlansWorkoutPlanIdResponse404 = {
  data: GetWorkoutPlansWorkoutPlanId404
  status: 404
}

export type getWorkoutPlansWorkoutPlanIdResponse500 = {
  data: GetWorkoutPlansWorkoutPlanId500
  status: 500
}

export type getWorkoutPlansWorkoutPlanIdResponseSuccess = (getWorkoutPlansWorkoutPlanIdResponse200) & {
  headers: Headers;
};
export type getWorkoutPlansWorkoutPlanIdResponseError = (getWorkoutPlansWorkoutPlanIdResponse401 | getWorkoutPlansWorkoutPlanIdResponse404 | getWorkoutPlansWorkoutPlanIdResponse500) & {
  headers: Headers;
};

export type getWorkoutPlansWorkoutPlanIdResponse = (getWorkoutPlansWorkoutPlanIdResponseSuccess | getWorkoutPlansWorkoutPlanIdResponseError)

export const getGetWorkoutPlansWorkoutPlanIdUrl = (workoutPlanId: string,) => {




  return `/workout-plans/${workoutPlanId}`
}

export const getWorkoutPlansWorkoutPlanId = async (workoutPlanId: string, options?: RequestInit): Promise<getWorkoutPlansWorkoutPlanIdResponse> => {

  return customFetch<getWorkoutPlansWorkoutPlanIdResponse>(getGetWorkoutPlansWorkoutPlanIdUrl(workoutPlanId),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Get a workout day
 */
export type getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponse200 = {
  data: GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId200
  status: 200
}

export type getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponse401 = {
  data: GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId401
  status: 401
}

export type getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponse404 = {
  data: GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId404
  status: 404
}

export type getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponse500 = {
  data: GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId500
  status: 500
}

export type getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponseSuccess = (getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponse200) & {
  headers: Headers;
};
export type getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponseError = (getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponse401 | getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponse404 | getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponse500) & {
  headers: Headers;
};

export type getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponse = (getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponseSuccess | getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponseError)

export const getGetWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdUrl = (workoutPlanId: string,
    workoutDayId: string,) => {




  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}`
}

export const getWorkoutPlansWorkoutPlanIdDaysWorkoutDayId = async (workoutPlanId: string,
    workoutDayId: string, options?: RequestInit): Promise<getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponse> => {

  return customFetch<getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponse>(getGetWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdUrl(workoutPlanId,workoutDayId),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Start a workout session
 */
export type postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse201 = {
  data: PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions201
  status: 201
}

export type postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse401 = {
  data: PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions401
  status: 401
}

export type postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse404 = {
  data: PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions404
  status: 404
}

export type postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse409 = {
  data: PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions409
  status: 409
}

export type postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse422 = {
  data: PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions422
  status: 422
}

export type postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse500 = {
  data: PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions500
  status: 500
}

export type postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponseSuccess = (postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse201) & {
  headers: Headers;
};
export type postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponseError = (postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse401 | postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse404 | postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse409 | postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse422 | postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse500) & {
  headers: Headers;
};

export type postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse = (postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponseSuccess | postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponseError)

export const getPostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsUrl = (workoutPlanId: string,
    workoutDayId: string,) => {




  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions`
}

export const postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions = async (workoutPlanId: string,
    workoutDayId: string, options?: RequestInit): Promise<postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse> => {

  return customFetch<postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse>(getPostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsUrl(workoutPlanId,workoutDayId),
  {
    ...options,
    method: 'POST'


  }
);}



/**
 * @summary Update a workout session
 */
export type patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponse200 = {
  data: PatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionId200
  status: 200
}

export type patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponse401 = {
  data: PatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionId401
  status: 401
}

export type patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponse404 = {
  data: PatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionId404
  status: 404
}

export type patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponse500 = {
  data: PatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionId500
  status: 500
}

export type patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponseSuccess = (patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponse200) & {
  headers: Headers;
};
export type patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponseError = (patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponse401 | patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponse404 | patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponse500) & {
  headers: Headers;
};

export type patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponse = (patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponseSuccess | patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponseError)

export const getPatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdUrl = (workoutPlanId: string,
    workoutDayId: string,
    sessionId: string,) => {




  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${sessionId}`
}

export const patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionId = async (workoutPlanId: string,
    workoutDayId: string,
    sessionId: string,
    patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdBody: PatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdBody, options?: RequestInit): Promise<patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponse> => {

  return customFetch<patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponse>(getPatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdUrl(workoutPlanId,workoutDayId,sessionId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdBody,)
  }
);}



/**
 * @summary Get home page data
 */
export type getHomeDateResponse200 = {
  data: GetHomeDate200
  status: 200
}

export type getHomeDateResponse401 = {
  data: GetHomeDate401
  status: 401
}

export type getHomeDateResponse404 = {
  data: GetHomeDate404
  status: 404
}

export type getHomeDateResponse500 = {
  data: GetHomeDate500
  status: 500
}

export type getHomeDateResponseSuccess = (getHomeDateResponse200) & {
  headers: Headers;
};
export type getHomeDateResponseError = (getHomeDateResponse401 | getHomeDateResponse404 | getHomeDateResponse500) & {
  headers: Headers;
};

export type getHomeDateResponse = (getHomeDateResponseSuccess | getHomeDateResponseError)

export const getGetHomeDateUrl = (date: string,) => {




  return `/home/${date}`
}

export const getHomeDate = async (date: string, options?: RequestInit): Promise<getHomeDateResponse> => {

  return customFetch<getHomeDateResponse>(getGetHomeDateUrl(date),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Get user workout stats
 */
export type getStatsResponse200 = {
  data: GetStats200
  status: 200
}

export type getStatsResponse401 = {
  data: GetStats401
  status: 401
}

export type getStatsResponse404 = {
  data: GetStats404
  status: 404
}

export type getStatsResponse500 = {
  data: GetStats500
  status: 500
}

export type getStatsResponseSuccess = (getStatsResponse200) & {
  headers: Headers;
};
export type getStatsResponseError = (getStatsResponse401 | getStatsResponse404 | getStatsResponse500) & {
  headers: Headers;
};

export type getStatsResponse = (getStatsResponseSuccess | getStatsResponseError)

export const getGetStatsUrl = (params: GetStatsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/stats/?${stringifiedParams}` : `/stats/`
}

export const getStats = async (params: GetStatsParams, options?: RequestInit): Promise<getStatsResponse> => {

  return customFetch<getStatsResponse>(getGetStatsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Get user train data
 */
export type getMeResponse200 = {
  data: GetMe200
  status: 200
}

export type getMeResponse401 = {
  data: GetMe401
  status: 401
}

export type getMeResponse500 = {
  data: GetMe500
  status: 500
}

export type getMeResponseSuccess = (getMeResponse200) & {
  headers: Headers;
};
export type getMeResponseError = (getMeResponse401 | getMeResponse500) & {
  headers: Headers;
};

export type getMeResponse = (getMeResponseSuccess | getMeResponseError)

export const getGetMeUrl = () => {




  return `/me/`
}

export const getMe = async ( options?: RequestInit): Promise<getMeResponse> => {

  return customFetch<getMeResponse>(getGetMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Upsert user train data
 */
export type putMeResponse200 = {
  data: PutMe200
  status: 200
}

export type putMeResponse401 = {
  data: PutMe401
  status: 401
}

export type putMeResponse500 = {
  data: PutMe500
  status: 500
}

export type putMeResponseSuccess = (putMeResponse200) & {
  headers: Headers;
};
export type putMeResponseError = (putMeResponse401 | putMeResponse500) & {
  headers: Headers;
};

export type putMeResponse = (putMeResponseSuccess | putMeResponseError)

export const getPutMeUrl = () => {




  return `/me/`
}

export const putMe = async (putMeBody: PutMeBody, options?: RequestInit): Promise<putMeResponse> => {

  return customFetch<putMeResponse>(getPutMeUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      putMeBody,)
  }
);}



/**
 * Hello World
 */
export type getResponse200 = {
  data: Get200
  status: 200
}

export type getResponseSuccess = (getResponse200) & {
  headers: Headers;
};
;

export type getResponse = (getResponseSuccess)

export const getGetUrl = () => {




  return `/`
}

export const get = async ( options?: RequestInit): Promise<getResponse> => {

  return customFetch<getResponse>(getGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}
